exclude = [
  "cliff.toml",
  "release.toml",
]

[formatting]
array_auto_collapse  = false
array_auto_expand    = true
array_trailing_comma = true

align_comments = true
align_entries  = true

compact_arrays        = false
compact_entries       = false
compact_inline_tables = false

inline_table_expand = true

column_width = 40

indent_entries = false
indent_tables  = false

trailing_newline = true

reorder_arrays        = true
reorder_inline_tables = true
reorder_keys          = true

allowed_blank_lines = 1

crlf = false
